{% set name = "dlpoly-py" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0ee2fb76a80ebdae356417e5a9bab3784839341103ed59feaa77386fe3b39ba

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - sphinx
  run:
    - python >=3.6
    - numpy >=1.5.0
    - matplotlib-base >=2.0.0
    - flake8
    - ruamel.yaml
    - coverage
    - pytest
    - pytest-cov
    - tox
    - sphinx

test:
  imports:
    - dlpoly

about:
  home: https://gitlab.com/drFaustroll/dlpoly-py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: dlpoly4 python module for file manipulation
  description: |
    dlpoly-py contains tools to read input and output for DL_POLY it can 
    also produce inputs and be mixed with other python packages like ASE, 
    MDAnalysis, MDAnse or pymatgen
  dev_url: https://gitlab.com/drFaustroll/dlpoly-py

extra:
  recipe-maintainers:
    - yafshar
